version: '2.1'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./public/system/:/app/public/system/
    ports:
      - 4000:4000
  nginx:
    volumes:
      - ./nginx.devel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  db_backup:
    command: /bin/true
