default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  host: localhost
  <<: *default


test:
  <<: *default
  host: localhost
  database: datagram_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
