development:
  sessions:
    default:
      database: dekko_development
      hosts:
        - localhost:27017
      options:
  options:
    # include_root_in_json: false
    # include_type_for_serialization: false
    # preload_models: false
    # protect_sensitive_fields: true
    # raise_not_found_error: true
    # scope_overwrite_exception: false
    # use_activesupport_time_zone: true
    # use_utc: false
test:
  sessions:
    default:
      database: dekko_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
